models/book.py
from extensions import db


class Author(db.Model):
    __tablename__ = 'authors'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(11))
    books = db.relationship('Book',backref='author')
    def __repr__(self):
        return "<Author id:%s name:%s>" % (self.id, self.name)

class Book(db.Model):
    __tablename__ = 'books'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(20))
    author_id = db.Column(db.Integer,db.ForeignKey('authors.id'))
    def __repr__(self):
        return "<Book id:%s name:%s author_id:%s>" % (self.id, self.name, self.author_id)

models/user.py
from extensions import db


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(11))

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(11))
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))

__init__.py
import os

from flask import Flask
from .extensions import db
from .routes.main import main
from .models import user, book
def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:root@127.0.0.1/book'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    # app.config['UPLOADED_PHOTOS_DEST'] = os.getcwd()
    db.init_app(app)
    app.secret_key = 'zhang'
    app.register_blueprint(main)
    db.create_all(app=app)
    return app

routes/book.py
from flask import Blueprint,render_template, flash, request, redirect, url_for
from models.book import Author, Book
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from extensions import db

book = Blueprint('book',__name__,template_folder='../templates/book',static_folder='static/book')

class SearchForm(FlaskForm):
    author = StringField('作者',validators=(DataRequired(),))
    book = StringField('书名',validators=(DataRequired(),))
    submit = SubmitField('添加书籍')

@book.route('/',methods=['GET','POST'])
def index():
    searchForm = SearchForm()
    if searchForm.validate_on_submit():
        author_name = searchForm.author.data
        book_name = searchForm.book.data
        author_query = Author.query.filter(Author.name == author_name).first()
        #作者不存在，直接添加作者和书籍
        if not author_query:
            try:
                author = Author(name=author_name)
                #先添加作者，自动生成作者id
                db.session.add(author)
                db.session.commit()
                book = Book(name=book_name, author_id=author.id)
                db.session.add(book)
                db.session.commit()
                flash("作者和书籍添加成功")
            except Exception as e:
                print(e)
                flash('添加作者和书籍失败')
                db.session.rollbak()
        #作者存在，看对应书籍是否存在
        else:
            #对应书籍不存在，添加书籍
            if not Book.query.filter_by(name=book_name).first():
                try:
                    book = Book(name=book_name, author_id=author_query.id)
                    db.session.add(book)
                    db.session.commit()
                    flash("书籍添加成功")
                except Exception as e:
                    print(e)
                    flash('添加书籍失败')
                    db.session.rollbak()
            #对应书籍存在，提示‘书籍已存在’
            else:
                flash("书籍已存在")
    else:
        if request.method == "POST":
            flash("信息填写有误")
    authors = Author.query.all()
    return render_template("books.html", authors=authors, searchform=searchForm)

@book.route("/deletebook/<book_id>")
def deletebook(book_id):
    book = Book.query.get(book_id)
    if book:
        try:
            db.session.delete(book)
            db.session.commit()
            flash("书籍已删除")
        except Exception as e:
            print(e)
            db.session.rollback()
            flash("删除书籍出错")
    else:
        flash("找不到对应书籍")
    return redirect(url_for("book.index"))

@book.route("/deletauthor/<author_id>")
def deleteauthor(author_id):
    author = Author.query.get(author_id)
    if author:
        try:
            Book.query.filter_by(author_id=author.id).delete()
            db.session.delete(author)
            db.session.commit()
            flash("作者及其书籍已删除")
        except Exception as e:
            print(e)
            db.session.rollback()
            flash("删除作者及其书籍出错")
    else:
        flash("找不到对应作者")
    return redirect(url_for("book.index"))

routes/main.py
from flask import Blueprint, render_template as rt, request, flash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo
from tools import img
# from flask_uploads import UploadSet, IMAGES
from extensions import db

main = Blueprint('main', __name__)
# photos = UploadSet('photos', IMAGES)

class LoginForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired()])
    password = PasswordField('密码', validators=[DataRequired()])
    confirm = PasswordField('确认密码', validators=[DataRequired(), EqualTo("password", "密码不一致")])
    submit = SubmitField('提交')


@main.route('/',methods=['GET','POST'])
def index():
    login_form = LoginForm()
    if request.method == 'POST':
        if login_form.validate_on_submit():
            return "success"
        else:
            flash('信息有误')
    return rt('login.html', form=login_form)


@main.route('/zhang/<int:name>')
def with_param(**n):
    return "name = %s" % n.get('name')


@main.route('/upload',methods=['GET','POST'])
def upload():
    if request.method == "POST":
        file = request.files.get('image')
        file.save("./image/back.jpg")
        img.compos('./image/back.jpg', './image/fore_1.jpg', './image/fore_2.jpg')
        return rt("image_res.html")
    return rt("upload.html")
    # if request.method == "POST":
    #     file = request.files.get('image')
    #     photos.save(file, 'test.jpg')
    #     file.save("../image/back.jpg")
    #     img.compos('../image/back.jpg', '../image/fore_1.jpg', '../image/fore_2.jpg')
    #     return rt("image_res.html")
    # return rt("upload.html")

templates/book/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book</title>
</head>
<body>
<form method="post">
    {{searchform.csrf_token()}}
    {{searchform.author.label}}{{searchform.author}}
    {{searchform.book.label}}{{searchform.book}}
    {{searchform.submit}}
    {% for message in get_flashed_messages() %}
    {{ message }}
    {% endfor %}
</form>
<ul>
    {% for author in authors %}
    <li>{{ author.name }}<a href="{{ url_for("book.deleteauthor",author_id=author.id) }}">删除</a></li>
    <ul>
        {% for book in author.books %}
        <li>{{book.name}}<a href="{{ url_for("book.deletebook",book_id=book.id) }}">删除</a> </li>
        {% else %}
        <li>无</li>
        {% endfor %}
    </ul>
    {% else %}
    <li>无</li>
    {% endfor %}
</ul>
</body>
</html>

templates/drag.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
    .container{
      width: 200px;
      height: 300px;
      background: #ff0000;
    }

    .item{
      width: 200px;
      height: 100px;
      background: pink;
    }

    .dragOver{
      background: rgba(255, 0, 0, 0.5);
    }
    .hidden{
      display: none;
    }
  </style>
</head>
<body>
  <div class="container" id='container' ondragleave="dragleave()" ondragenter="dragenter()" ondrop="drop()" ondragover="dragover()"></div>
  <div class="item" draggable="true" ondragstart="dragStart()" id="item"></div>
  <img src="../image/fore_1.png" class="hidden"/>
  <script>
    function dragStart(e){
      e.dataTransfer.setData('id', e.target.id);
      let image = document.querySelector('img').cloneNode();
      image.classList.remove('hidden');
      e.dataTransfer.setDragImage(image,150,150);
    }

    function drop(e){
      e.preventDefault();
      let id = e.dataTransfer.getData('id');
      e.target.appendChild(document.getElementById(id));
    }

    function dragover(e){
      e.preventDefault();
      e.target.classList.add('dragOver');
    }

    function dragleave(e){
      console.log('leave');
      e.target.classList.remove('dragOver');
    }
  </script>
</body>
</html>

templates/image_res.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>image result</title>
</head>
<body>
<img src="{{ url_for('static',filename='compos.png') }}">
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
<h1>登录页面</h1>
{# <form method="post">
    用户名:<input type="text" name="username"><br>
    密码:<input type="text" name="password">
    <input type="submit" value="提交">
</form>
#}
<form method="post">
    {{form.csrf_token}}
    {{form.username.label}}{{form.username}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.confirm.label}}{{form.confirm}}<br>
    {{form.submit}}<br>
</form>
{% for message in get_flashed_messages() %}
{{message}}
{% endfor %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">

    <title>主页</title>
    <link rel="stylesheet" href="/static/login.css">
    <link rel="shortcut icon" href="/static/images/owl-icon.png">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(function(){
            $('#password').focus(function(){
                // 密码框获得焦点，追加样式.password
                $('#owl').addClass('password');
            }).blur(function(){
                // 密码框失去焦点，移除样式.password
                $('#owl').removeClass('password');
            })
        })
    </script>
</head>

<body>
    <div class="login-box">
        <div class="owl" id="owl">
            <div class="hand"></div>
            <div class="hand hand-r"></div>
            <div class="arms">
                <div class="arm"></div>
                <div class="arm arm-r"></div>
            </div>
        </div>
        <div class="input-box">
            <input type="text" placeholder="账号">
            <input type="password" placeholder="密码" id="password">
            <button>登录</button>
        </div>
    </div>
</body>

</html>

templates/upload.html
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0">
    <title>upload</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='upload.css')}}">
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    <input id="img_src" type="file" name="image" accept="image/*" onchange="showImg()"><br>
    <img style="height:300px" src="static/images/ghost.gif" id="img_show"><br>
    <input type="submit" value="提交"><br>
</form>
<div id="msg"></div>
</body>
<script>

    function showImg(){
        var file = document.getElementById("img_src").files[0];
        var fr = new FileReader();
        fr.readAsDataURL(file);
        fr.onload = function(fr){
            document.getElementById("img_show").src = fr.target.result;
        }
        var fd = new FormData();
        fd.append('file',file);
        console.log('file',fd.get('file'))
    }
</script>
</html>